### PR TITLE
My solution to princesses and dragons

### PR DESCRIPTION
**Pull request by vanderfred**
also added unittests

### CODE REVIEW

**Comment by idlv75** [comment]
Can you please explain how your script can be executed in **any** environment?

**Comment by vanderfred** [comment]
I guess because it's written in Python, which doesn't have compiler, but does have an interpreter, it translates script to specific machine code, and thus it will work in any environment

**Comment by idlv75** [comment]
$ git fetch origin pull/16/head:vanderfred
$ git checkout vanderfred
$ ls
input.yaml  LICENSE  princesses_and_dragons.py  README.md  run_test.py

# Stuck. Does not execute
$ chmod +x princesses_and_dragons.py 
$ ./princesses_and_dragons.py  # 

# Crushes
$ python3 ./princesses_and_dragons.py 
Traceback (most recent call last):
  File "./princesses_and_dragons.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by vanderfred** [comment]
fixed

**Comment by idlv75** [comment]
Let's try again.
How can you have the code use the "yaml" library and be executable at the same time in any environment.
HINT: There is a standard Python solution for scenarios like this.

**Comment by vanderfred** [comment]
I thought about venv solution or about installing modules via pip before including them, but I understood that anyway yaml library doesn't help me a lot and I can handle without using it. So I decided to get rid off it.

**Comment by idlv75** [comment]
DNP

**Comment by idlv75** [comment]
DNP

**Pull request closed without merging**
