### PR TITLE
My solution to codeforce 548

### PR DESCRIPTION
**Pull request by acocaori**

### CODE REVIEW

**Comment by idlv75** [comment]
Please explain how this script can be executed in Linux environment without sudo permissions.

**Comment by acocaori** [comment]
--------------------------------------------------------------------------------------------------------------------------------------

[root@ip-10-0-0-53 ec2-user]# useradd test_user
[root@ip-10-0-0-53 ec2-user]# su test_user
[test_user@ip-10-0-0-53 ec2-user]$ whoami
test_user
[test_user@ip-10-0-0-53 ec2-user]$ sudo -v
Sorry, user test_user may not run sudo on ip-10-0-0-53.


--------------------------------------------------------------------------------------------------------------------------------------

non-root users should execute from the user's home directory.
It has the required priviledges to execute scripts by default and serves as the repository for the user's personal files.
It is configured upon the user creation with the below enviornment variable:

Note: we can execute from "/tmp/" as well.

This directory is different than the "/root" directory which is associated with the root user.

[test_user@ip-10-0-0-53 ec2-user]$ echo $HOME
/home/test_user



1. change directory to user's home directory:

	Few options here:

	a. using the "tilde" which represents the user's home directory in unix-like systems:
	[test_user@ip-10-0-0-53 bin]$ cd ~/
	[test_user@ip-10-0-0-53 ~]$ pwd
	/home/test_user

	b. using the related env variable:
	[test_user@ip-10-0-0-53 bin]$ cd $HOME
	[test_user@ip-10-0-0-53 ~]$ pwd
	/home/test_user



2. clone the git repository to the local system:

[test_user@ip-10-0-0-53 ~]$ git clone https://github.com/acocaori/dragons-and-princesses.git
Cloning into 'dragons-and-princesses'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 6), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), 6.11 KiB | 1.53 MiB/s, done.



3. change directory into the project's directory:

[test_user@ip-10-0-0-53 ~]$ cd dragons-and-princesses/
[test_user@ip-10-0-0-53 dragons-and-princesses]$ pwd
/home/test_user/dragons-and-princesses


4. execute the script:

[test_user@ip-10-0-0-53 dragons-and-princesses]$ python3 Dragons_and_Princesses.py 
13
2
3 5

**Comment by idlv75** [comment]
It works in your environment.
How can it work in any environment?

$ python3 ./Dragons_and_Princesses.py 
Traceback (most recent call last):
  File "./Dragons_and_Princesses.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by acocaori** [comment]
The best solution is to deploy as containerized application to avoid dependency hell.

**Comment by acocaori** [comment]
One more option is converting to standalone executable using Pyinstaller with the "--onefile" flag.

**Comment by acocaori** [comment]
FYI - executable file of the project was uploaded yesterday 
(possible solution in addition to running solution #1 (running as container).

**Comment by idlv75** [comment]
DNP

**Pull request closed without merging**
