### PR TITLE
Solution for interview

### PR DESCRIPTION
**Pull request by yuliakonev**

### CODE REVIEW

**Comment by idlv75** [comment]
Please explain how this script can be executed in **any** environment

**Comment by yuliakonev** [comment]
2 input files have been provided input1.yaml and input2.yaml. These input files contain the scenarios mentioned in the task.
Main script can be run as python solution.py where input1.yaml is hard coded for check.
The some unitest can be run as python tests_for_solution.py.
Let me know if the input yaml file should be passed as command line param and I will change the code.

**Comment by idlv75** [comment]
When I execute the code it fails:

$ python ./solution.py 
Traceback (most recent call last):
  File "/code/./solution.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

What can be done to make the code executable in any environment?

**Comment by yuliakonev** [comment]
I've changed the code.
Now the run commands are
python solution.py input1.yaml.  (first scenario)
python solution.py input2.yaml.  (second scenario)
python tests_for_solution.py

**Comment by idlv75** [comment]
Passed

**Pull request closed without merging**
