### PR TITLE
dragons and princess answer

### PR DESCRIPTION
**Pull request by dvdgitman**
made a solution for the dragons and princess exam

### CODE REVIEW

**Comment by idlv75** [comment]
You expect input in text format. Input needs to be in Yaml file format.
Please, change code accordingly and provide example of input file you are using for testing and validation

**Comment by dvdgitman** [comment]
> You expect input in text format. Input needs to be in Yaml file format.
> 
> Please, change code accordingly and provide example of input file you are using for testing and validation

Can I get An example of a yaml file input?

**Comment by idlv75** [comment]
You can look here: https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started/

**Comment by dvdgitman** [comment]
> You can look here: https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started/

ive added yaml as input file :)

**Comment by idlv75** [comment]
You are still reading the input file as text file: file.readline().
Loading yaml file is done with: yaml.load(file)

**Comment by dvdgitman** [comment]
> You are still reading the input file as text file: file.readline().
> Loading yaml file is done with: yaml.load(file)

Done as requested :)

**Comment by idlv75** [comment]
DNP

**Pull request closed without merging**
