### PR TITLE
My solution for the CodeForces problem #548

### PR DESCRIPTION
**Pull request by Avivshi**
I'd like to submit my solution for the CodeForces problem #548.
I added screenshots with examples of how to run the program with different input files.

I value your feedback, so let me know what you think :)

Thanks,
Aviv

### CODE REVIEW

**Comment by idlv75** [comment]
One of the exercise requirements was that the script can be executable:
./script ...
How can this be achieved?

**Comment by Avivshi** [comment]
I can use the pyinstaller module, I will commit a fix immediately

**Comment by Avivshi** [comment]
I committed the fix with additional changes.
In order to change the input for the .exe file you need to edit the input file located in input_file/input.yml

**Comment by idlv75** [comment]
DNP

**Pull request closed without merging**
