### PR TITLE
#548 submission

### PR DESCRIPTION
**Pull request by ohgrad**
Here is the solution for the following problem.
Cheers

### CODE REVIEW

**Comment by idlv75** [comment]
Why you are not using the standard python yaml library to read the input file?

**Comment by ohgrad** [comment]
The reason i didnt use the "python yaml" is becasue i was not sure what are the spec to run the code. Therefore i have decided to not use pip packages and only write my code with the the python standard libraries with the latest python version.

**Comment by idlv75** [comment]
DNP

**Comment by ohgrad** [comment]
why the branch do not pass if the task was never asking specifically to use a yaml package?
The code is ticking all the requested points. if you had intension to use a package, this should be clearly defined in the task since this looks like a mystery to your tricky question that not measuring much of a skills here.

**Pull request closed without merging**
