### PR TITLE
Providing a solution for the CodeForces problem #548.

### PR DESCRIPTION
**Pull request by matanmula172**
Code is implemented in Python (solution.py)
Input is consumed as yaml file, input example provided (input_file.yaml)

### CODE REVIEW

**Comment by idlv75** [comment]
Please explain how this script can be executed in **any** environment

**Comment by matanmula172** [comment]
It doesn't. After i realized you wanted a program that could be executed in any environment i created an exe file (using pyinstaller) with a basic user interface.
I also added a powerpoint guide that explains how to use it (if necessary).
I already pushed the changes, so you can view them.

**Comment by idlv75** [comment]
You are killing me.
You worked really hard to provide a solution that is still platform specific:

$ file ./dist/solution.exe 
./dist/solution.exe: **PE32 executable (console) Intel 80386, for MS Windows**

What about Linux, Debian, FreeBSD, Solaris, etc. ???

Python is an interpreted language that can be executed on any OS. Up to providing the necessary libraries.
Very similar to JAVA in this aspect.
In our case you just had to take care of deploying the PyYaml package, because it is not part of the standard Python interpreter.
This is done with pip.

**Comment by matanmula172** [comment]
I understad. For that reason (and for several others) i didn't use the PyYaml package.
I hope you still looked at the code and ran the solution file.

**Pull request closed without merging**
